DROP DATABASE IF EXISTS IRCUSTOMERS;
CREATE DATABASE IRCUSTOMERS;

USE IRCUSTOMERS;

DROP TABLE IF EXISTS CUSTOMERS;
CREATE TABLE CUSTOMERS (
    CUSTOMERS_ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(30) NOT NULL,
    LASTNAME VARCHAR(30) NOT NULL,
    BIRTHDAY DATETIME NOT NULL
);

DROP TABLE IF EXISTS PROPERTIES;
CREATE TABLE PROPERTIES (
	PROPERTIES_ID BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NAME VARCHAR(100) NOT NULL,
	VALUE VARCHAR(100)
);

INSERT INTO PROPERTIES (NAME, VALUE) VALUES ('customers.life.expectancy', '75');

DELIMITER $$
CREATE DEFINER=`root`@`localhost` FUNCTION `f_year_diff`(dateA date, dateB date)
RETURNS int(11)
DETERMINISTIC
BEGIN
   DECLARE diff INT;
   SET diff =  TIMESTAMPDIFF(YEAR, dateA, dateB);
   RETURN diff;
END$$
DELIMITER ;

DELIMITER $$
CREATE DEFINER=`root`@`localhost` FUNCTION `f_current_year_diff`(dateA date)
RETURNS int(11)
DETERMINISTIC
BEGIN
   DECLARE diff INT;
   SET diff =  f_year_diff(dateA, current_date());
   RETURN diff;
END$$
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE usp_std_customer_age()
BEGIN
	SELECT STD(age) std_age
	FROM (
		SELECT f_year_diff(BIRTHDAY, CURRENT_DATE()) age
		FROM customers c 
	) s;
END$$
DELIMITER ;
